# Generated by Django 5.2.17 on 2026-09-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('license_class', models.CharField(choices=[('cdl_a', 'CDL Class A'), ('cdl_b', 'CDL Class B')], max_length=10)),
                ('years_experience', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('freight_type', models.CharField(choices=[('ftl', 'Full Truckload (FTL)'), ('ltl', 'Less Than Truckload (LTL)'), ('reefer', 'Refrigerated (Reefer)'), ('flatbed', 'Flatbed / Oversized'), ('dedicated', 'Dedicated Fleet'), ('other', 'Other')], max_length=20)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
