# Generated by Django 5.2.17 on 2026-10-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverapplication',
            name='license_class',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='years_experience',
        ),
    ]
